In [4]:
pwd

u'C:\\Users\\kusha'

In [2]:
!python --version

Python 2.7.15 :: Anaconda, Inc.


In [5]:
import numpy as np
x = np.array([1, 2, 4, 7, 0])
np.ediff1d(x)

array([ 1,  2,  3, -7])

In [10]:
x = np.array([1, 17, 5, 10, 13, 15, 10, 5, 16, 8])
np.ediff1d(x)

array([ 16, -12,   5,   3,   2,  -5,  -5,  11,  -8])

In [11]:
l= len(np.ediff1d(x))

In [12]:
l


9

In [13]:
x = np.array([1, 17, 5, 10, 13, 15, 10, 5, 16, 8])
np.ediff1d(x)

array([ 16, -12,   5,   3,   2,  -5,  -5,  11,  -8])

In [14]:
l= len(np.ediff1d(x))

In [15]:
l

9